export enum HttpStatusCode {
  OK = 200,
  CREATED = 201,
  NO_CONTENT = 204,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  CONFLICT = 409,
  UNPROCESSABLE_ENTITY = 422,
  TOO_MANY_REQUESTS = 429,
  INTERNAL_SERVER_ERROR = 500,
  SERVICE_UNAVAILABLE = 503,
}

export enum ErrorCode {
  VALIDATION_ERROR = "VALIDATION_ERROR",
  INVALID_INPUT = "INVALID_INPUT",

  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  TOKEN_EXPIRED = "TOKEN_EXPIRED",
  INVALID_TOKEN = "INVALID_TOKEN",

  NOT_FOUND = "NOT_FOUND",
  ALREADY_EXISTS = "ALREADY_EXISTS",
  DUPLICATE_KEY = "DUPLICATE_KEY",

  DATABASE_ERROR = "DATABASE_ERROR",
  MONGO_VALIDATION_ERROR = "MONGO_VALIDATION_ERROR",
  MONGO_DUPLICATE_KEY = "MONGO_DUPLICATE_KEY",

  RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",

  INTERNAL_ERROR = "INTERNAL_ERROR",
  SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE",

  SESSION_EXPIRED = "SESSION_EXPIRED",
  DEVICE_MISMATCH = "DEVICE_MISMATCH",
}

export enum SortDirection {
  ASC = 1,
  DESC = -1,
}

export * from "./circle.enums";
export * from "./ledger.enums";
